import { saveAbout } from "../../actions";
import { requireAdmin } from "@/lib/admin";
import styles from "../../admin.module.css";

export default async function AdminAboutPage({ searchParams }: { searchParams:Promise<{saved?:string}> }) {
  const { supabase } = await requireAdmin(); const [{ data }, query] = await Promise.all([supabase.from("site_settings").select("value").eq("key","about").maybeSingle(),searchParams]);
  const value = (data?.value ?? {}) as Record<string,string>;
  return <><div className={styles.heading}><div><h1>About page</h1><p>Ted can rewrite the page and replace his portrait at any time.</p></div></div>{query.saved ? <p className={styles.notice}>About page updated.</p> : null}<form className={styles.form} action={saveAbout} encType="multipart/form-data"><input type="hidden" name="existing_image" value={value.image_url ?? ""}/><div className={styles.field}><label htmlFor="heading">Main heading</label><input id="heading" name="heading" defaultValue={value.heading} required/></div><div className={styles.field}><label htmlFor="intro">Introduction</label><textarea id="intro" name="intro" defaultValue={value.intro}/></div><div className={styles.field}><label htmlFor="body">Career and story</label><textarea id="body" name="body" defaultValue={value.body}/></div><div className={styles.field}><label htmlFor="secondary">Second paragraph</label><textarea id="secondary" name="secondary" defaultValue={value.secondary}/></div><div className={styles.field}><label htmlFor="closing_heading">Closing heading</label><input id="closing_heading" name="closing_heading" defaultValue={value.closing_heading}/></div><div className={styles.field}><label htmlFor="closing_body">Closing paragraph</label><textarea id="closing_body" name="closing_body" defaultValue={value.closing_body}/></div><div className={styles.field}><label htmlFor="image">New portrait (optional)</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp"/></div><button className={styles.primary}>Save About page</button></form></>;
}
